#!/usr/env/python
""" :: Satyrus III ::
    =================
"""
## Standard Library
import argparse

## Local
from satyrus.sat_core import load, stream, stdout, stderr, stdsys, Source
from satyrus.sat_compiler import SatCompiler
from satyrus.sat_parser import SatParser

class Satyrus:

    @classmethod
    def main(cls, *args, **kwargs):
        cls.source = Source.load(cls.fname)
        stdsys[1] << ":: Source Code ::"
        cls.print_code(cls.source.lines)

        cls.parser = SatParser(cls.source)
        stdsys[1] << ":: SATyrus bytecode ::"
        cls.parser.parse()

        cls.compiler = SatCompiler(cls.source)
        cls.compiler.compile()

        
        

        
        cls.print_code(cls.bytecode)
        return

    @classmethod
    def print_code(cls, code : list):
        nlines = len(code)
        for i, line in enumerate(code, 1):
            stdout[1] << f"{str(i).zfill(len(str(nlines)))} {line}"
        
    @classmethod
    def init(cls, fname):
        cls.fname = fname

if __name__ == '__main__':
    Satyrus.init('source.sat')
    Satyrus.main()