from .main import SYS_CONFIG, DEF_CONSTANT, DEF_ARRAY, DEF_CONSTRAINT
from .main import CONS_INT, CONS_OPT, RUN_INIT, RUN_SCRIPT, CMD_PYTHON, CMD_INIT, CMD_SCRIPT
from .main import PREC, DIR, LOAD, OUT, OPT, EPSILON, ALPHA, EXIT, MAPPING, INDEXER